.\" debsecan - Debian Security Analyzer
.\" Copyright (C) 2005 Florian Weimer
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.\"
.TH DEBSECAN 1 2005-12-14 "" ""
.SH NAME
debsecan \- Debian Security Analyzer
.SH SYNOPSIS
.B debsecan
.B --suite
.I suite
.I options...
.SH DESCRIPTION
.B debsecan
analyzes the list of installed packages on the current host and
reports vulnerabilities found on the system.
.SH OPTIONS
.TP
.B --suite \fIcount\fP
This mandatory option tells
.B debsecan
which Debian suite (release) should be used.  The release code name
has to be used ("sid"), not the temporal name ("unstable").  Due to
the way
.B debsecan
works, the correct suite must be specified, otherwise the results are
incorrect.  See
.SM
.B CAVEATS
below for details.
.TP
.B --source \fIurl\fP
Override the default download URL for vulnerability data.
.B --status \fIfile\fP
Evaluate a different
.B dpkg
status file.
.TP
.B --format \fIformat\fP
Change the output format.  If
.I format
is
.B summary
(the default), a short summary for each vulnerability is printed.
For
.B bugs
and
.BR packages ,
.B debsecan
lists the names of vulnerabilities and binary packages, respectively.
.TP
.B --help
Display a short help message exists.
.TP
.B --version
Display version information and exists.
.SH "CAVEATS"
Versions of Debian packages which are part of different releases are
not comparable in the sense that the comparison yields useful
information.  For example, all packages in the stable suite have
versions which are not greater than the version in unstable.  This is
true even if a security update has been applied to the stable suite.
In this case, the simple version-based algorithm used by
.B debsecan
would incorrectly flag the vulnerable package version from unstable as
fixed when vulnerability data for the stable suite is used to rate the
system.
.P
This is the reason why Debian installations which mix packages from
multiple releases
.B "are not supported" .
If in doubt, specify
.B --release sid
when invoking
.BR debsecan .
This will result in some false positives, but not in false negatives.
.SH AUTHOR
.B debsecan
was written by Florian Weimer.
.SH "SEE ALSO"
.BR dpkg "(1)"
.BR pcrepattern "(3),"
