#!/usr/bin/python

import sys
import zlib
import urllib2
from cStringIO import StringIO

url_prefix = 'http://secure-testing.debian.net/debian-secure-testing/project/debsecan/release/1/'

if len(sys.argv) <> 2:
    print "usage: %s SUITE" 

url = url_prefix + sys.argv[1]
r = urllib2.Request(url)
u = urllib2.urlopen(r)
data = StringIO(zlib.decompress(u.read()))

if data.readline() <> "VERSION 1\n":
    sys.stderr.write("error: server sends data in unknown format\n")
    sys.exit(1)

vuln_names = []
for line in data:
    if line[-1:] == '\n':
        line = line[:-1]
    if line == '':
        break
    (name, flags, desc) = line.split(',', 2)
    vuln_names.append(name)

for line in data:
    if line[-1:] == '\n':
        line = line[:-1]
    if line == '':
        break
    (package, vuln, rest) = line.split(',', 2)
    vuln = vuln_names[int(vuln)]
    print "%s,%s,%s" % (package, vuln, rest)

for line in data:
    if line[-1:] == '\n':
        line = line[:-1]
    if line == '':
        break
    print line
